apiVersion: v1
kind: Pod
metadata:
  name: api-restaurante
  labels:
    app: api-restaurante
spec:
  containers:
    - name: api-restaurante-container
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: sistema-configmap
