apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-restaurante-deployment
spec:
  template:
    metadata:
      name: api-restaurante
      labels:
        app: api-restaurante
    spec:
      containers:
        - name: api-restaurante-container
          image: gabrielumbelino/restaurante-api:1.1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: api-restaurante-configmap
            - secretRef:
                name: db-secret
          livenessProbe:
            httpGet:
              path: /api
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /api
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 30m
  replicas: 1
  selector:
    matchLabels:
      app: api-restaurante
